# Generated by Django 4.2.20 on 2025-03-28 05:31

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='related_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='files.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
